export const LOAD_BANNERS_START = "LOAD_BANNERS_START"
export const LOAD_BANNERS_SUCCESS = "LOAD_BANNERS_SUCCESS"
export const LOAD_BANNERS_ERROR = "LOAD_BANNERS_ERROR"

export const GET_SINGLE_BANNER_START = 'GET_SINGLE_BANNER_START'
export const GET_SINGLE_BANNER_SUCCESS = 'GET_SINGLE_BANNER_SUCCESS'
export const GET_SINGLE_BANNER_ERROR = 'GET_SINGLE_BANNER_ERROR'

export const ADD_NEW_BANNER_START = 'ADD_NEW_BANNER_START'
export const ADD_NEW_BANNER_SUCCESS = 'ADD_NEW_BANNER_SUCCESS'
export const ADD_NEW_BANNER_ERROR = 'ADD_NEW_BANNER_ERROR'

export const UPDATE_BANNER_START = 'UPDATE_BANNER_START'
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS'
export const UPDATE_BANNER_ERROR = 'UPDATE_BANNER_ERROR'

export const DELETE_BANNER_START = 'DELETE_BANNER_START'
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS'
export const DELETE_BANNER_ERROR = 'DELETE_BANNER_ERROR'