
export const LOAD_CATEGORIES_START = "LOAD_CATEGORIES_START"
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS"
export const LOAD_CATEGORIES_ERROR = "LOAD_CATEGORIES_ERROR"

export const ADD_NEW_CATEGORY_START = 'ADD_NEW_CATEGORY_START'
export const ADD_NEW_CATEGORY_SUCCESS = 'ADD_NEW_CATEGORY_SUCCESS'
export const ADD_NEW_CATEGORY_ERROR = 'ADD_NEW_CATEGORY_ERROR'

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR'

export const GET_SINGLE_CATEGORY_START = 'GET_SINGLE_CATEGORY_START'
export const GET_SINGLE_CATEGORY_SUCCESS = 'GET_SINGLE_CATEGORY_SUCCESS'
export const GET_SINGLE_CATEGORY_ERROR = 'GET_SINGLE_CATEGORY_ERROR'

export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR'


