
export const LOAD_OFFERS_START = "LOAD_OFFERS_START"
export const LOAD_OFFERS_SUCCESS = "LOAD_OFFERS_SUCCESS"
export const LOAD_OFFERS_ERROR = "LOAD_OFFERS_ERROR"

export const ADD_NEW_OFFER_START = 'ADD_NEW_OFFER_START'
export const ADD_NEW_OFFER_SUCCESS = 'ADD_NEW_OFFER_SUCCESS'
export const ADD_NEW_OFFER_ERROR = 'ADD_NEW_OFFER_ERROR'

export const UPDATE_OFFER_START = 'UPDATE_OFFER_START'
export const UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS'
export const UPDATE_OFFER_ERROR = 'UPDATE_OFFER_ERROR'

export const GET_SINGLE_OFFER_START = 'GET_SINGLE_OFFER_START'
export const GET_SINGLE_OFFER_SUCCESS = 'GET_SINGLE_OFFER_SUCCESS'
export const GET_SINGLE_OFFER_ERROR = 'GET_SINGLE_OFFER_ERROR'
 
export const DELETE_OFFER_START = 'DELETE_OFFER_START'
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS'
export const DELETE_OFFER_ERROR = 'DELETE_OFFER_ERROR'
