export const LOAD_ORDERS_START = "LOAD_ORDERS_START"
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS"
export const LOAD_ORDERS_ERROR = "LOAD_ORDERS_ERROR"

export const GET_SINGLE_ORDER_START = 'GET_SINGLE_ORDER_START'
export const GET_SINGLE_ORDER_SUCCESS = 'GET_SINGLE_ORDER_SUCCESS'
export const GET_SINGLE_ORDER_ERROR = 'GET_SINGLE_ORDER_ERROR'

export const DELETE_ORDER_START = 'DELETE_ORDER_START'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR'