export const LOAD_PROFESSIONALS_START = "LOAD_PROFESSIONALS_START"
export const LOAD_PROFESSIONALS_SUCCESS = "LOAD_PROFESSIONALS_SUCCESS"
export const LOAD_PROFESSIONALS_ERROR = "LOAD_PROFESSIONALS_ERROR"

export const GET_SINGLE_PROFESSIONAL_START = 'GET_SINGLE_PROFESSIONAL_START'
export const GET_SINGLE_PROFESSIONAL_SUCCESS = 'GET_SINGLE_PROFESSIONAL_SUCCESS'
export const GET_SINGLE_PROFESSIONAL_ERROR = 'GET_SINGLE_PROFESSIONAL_ERROR'

export const DELETE_PROFESSIONAL_START = 'DELETE_PROFESSIONAL_START'
export const DELETE_PROFESSIONAL_SUCCESS = 'DELETE_PROFESSIONAL_SUCCESS'
export const DELETE_PROFESSIONAL_ERROR = 'DELETE_PROFESSIONAL_ERROR'