export const LOAD_SERVICES_START = "LOAD_SERVICES_START"
export const LOAD_SERVICES_SUCCESS = "LOAD_SERVICES_SUCCESS"
export const LOAD_SERVICES_ERROR = "LOAD_SERVICES_ERROR"

export const GET_SINGLE_SERVICE_START = 'GET_SINGLE_SERVICE_START'
export const GET_SINGLE_SERVICE_SUCCESS = 'GET_SINGLE_SERVICE_SUCCESS'
export const GET_SINGLE_SERVICE_ERROR = 'GET_SINGLE_SERVICE_ERROR'

export const ADD_NEW_SERVICE_START = 'ADD_NEW_SERVICE_START'
export const ADD_NEW_SERVICE_SUCCESS = 'ADD_NEW_SERVICE_SUCCESS'
export const ADD_NEW_SERVICE_ERROR = 'ADD_NEW_SERVICE_ERROR'

export const UPDATE_SERVICE_START = 'UPDATE_SERVICE_START'
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS'
export const UPDATE_SERVICE_ERROR = 'UPDATE_SERVICE_ERROR'

export const DELETE_SERVICE_START = 'DELETE_SERVICE_START'
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS'
export const DELETE_SERVICE_ERROR = 'DELETE_SERVICE_ERROR'